"""
Django settings for Mohini project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import json
import os
import re
from datetime import timedelta
import sentry_sdk
from dotenv import load_dotenv
from socket import gethostbyname
from socket import gethostname

load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CODE_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGGING_DIR = CODE_BASE_DIR + '/logs'

def load_secrets():
    paths_to_try = [
        '/home/ubuntu/shikshalokam-mohini-service/config/secrets.json',
        os.path.join(CODE_BASE_DIR, "config/secrets.json"),
        os.path.join(os.getcwd(), "config/secrets.json")
    ]

    for path in paths_to_try:
        print(f"[DEBUG] Trying secrets file at: {path}")
        try:
            with open(path, 'r') as f:
                print(f"[DEBUG] Loaded secrets from: {path}")
                return json.load(f), path
        except FileNotFoundError:
            print(f"[DEBUG] File not found at: {path}")
            continue

    raise FileNotFoundError(f"secrets.json not found in any of: {paths_to_try}")


SECRETS, SECRETS_JSON_PATH = load_secrets()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#7!xudzh7f@!yih9^l5d)my*$7=^j-@i#qla(k1mae5u(qs_c^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('SETTINGS_DEBUG') == 'True' else False

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'x-auth-token'
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS').split(',')

CORS_ALLOWED_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS'  # Include the OPTIONS method for preflight requests
]

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# ALLOWED_HOSTS.append(gethostbyname(gethostname()))


# Application definition

INSTALLED_APPS = [
    'rangefilter',
    'observability',
    'daphne',
    'chatbot',
    'shikshalokam',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'django_countries',
    'django_s3_storage',
    'import_export',
    'simple_history',
    'storages',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    ## extra middlwares
    'chatbot.middlewares.VerifyAuthToken'
]

if DEBUG:
    MIDDLEWARE.extend([
        'querycount.middleware.QueryCountMiddleware'
    ])


ROOT_URLCONF = 'shikshalokam_mohini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

QUERYCOUNT = {
    'DISPLAY_DUPLICATES': 5,
}

WSGI_APPLICATION = 'shikshalokam_mohini.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
        'OPTIONS': {
            'sslmode': os.getenv('PG_SSL_MODE'),
            'sslrootcert': os.getenv('PG_SSL_ROOT_CERT')
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', '/var/www/shikshalokam/static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'shikshalokam_mohini.asgi.application'

REDIS_HOST = os.environ.get('REDIS_HOST', "127.0.0.1")
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_USE_SSL = os.environ.get('REDIS_USE_SSL', 'false').lower() == 'true'

# Build Redis connection URL with SSL support
REDIS_PROTOCOL = 'rediss' if REDIS_USE_SSL else 'redis'
REDIS_URL = f'{REDIS_PROTOCOL}://{REDIS_HOST}:{REDIS_PORT}'

# Celery uses its own Redis database and a service-specific queue so a shared
# Redis instance never mixes this service's tasks with another service's
# (databases: 0 = channels, 1 = cache, 2 = celery broker/results)
REDIS_CELERY_DB = int(os.environ.get('REDIS_CELERY_DB', 2))
CELERY_BROKER_URL = f'{REDIS_URL}/{REDIS_CELERY_DB}'
CELERY_RESULT_BACKEND = f'{REDIS_URL}/{REDIS_CELERY_DB}'
CELERY_TASK_DEFAULT_QUEUE = os.environ.get('CELERY_TASK_DEFAULT_QUEUE', 'sg_commons_queue')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 100000,
            "channel_capacity": {
                "http.request": 50000,
                "http.response!*": 50000,
                re.compile(r"^websocket.send\!.+"): 100000,
            }
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',  # Use database 1 (different from channels)
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
                'health_check_interval': 30,
            },
            'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'TIMEOUT': 7200,
    }
}

# TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "https://*.shikshalokam.org,https://*.127.0.0.1,https://*.gritworks.ai,http://localhost:3000").split(',')

STORAGE_CLOUD_PROVIDER = os.environ.get('STORAGE_CLOUD_PROVIDER', 'AWS').upper()

# Storage backend configurations
STORAGE_BACKENDS = {
    'AWS': {
        'backend': 'storages.backends.s3boto3.S3Boto3Storage',
        'options': {
            'bucket_name': os.getenv('S3_BUCKET_NAME'),
            'region_name': os.getenv('AWS_REGION'),
        },
    },
    'GCP': {
        'backend': 'storages.backends.gcloud.GoogleCloudStorage',
        'options': {
            'bucket_name': os.getenv('GCS_BUCKET_NAME'),
            'project_id': os.getenv('GCP_PROJECT_ID'),
            'credentials': os.getenv('GCP_CREDENTIALS_PATH'),
        },
    },
    'AZURE': {
        'backend': 'storages.backends.azure_storage.AzureStorage',
        'options': {
            'account_name': os.getenv('AZURE_ACCOUNT_NAME'),
            'account_key': os.getenv('AZURE_ACCOUNT_KEY'),
            'azure_container': os.getenv('AZURE_CONTAINER_NAME'),
        },
    },
    'LOCAL': {
        'backend': 'django.core.files.storage.FileSystemStorage',
        'options': {
            'location': os.path.join(BASE_DIR, 'media'),
            'base_url': '/media/',
        },
    },
}

# Configure storage based on provider
if STORAGE_CLOUD_PROVIDER in STORAGE_BACKENDS:
    config = STORAGE_BACKENDS[STORAGE_CLOUD_PROVIDER]
    
    if STORAGE_CLOUD_PROVIDER == 'LOCAL':
        MEDIA_ROOT = config['options']['location']
        MEDIA_URL = config['options']['base_url']
        
        STORAGES = {
            "default": {
                "BACKEND": config['backend'],
                "OPTIONS": config['options'],
            },
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
            },
        }
    else:
        # For cloud storage (AWS/GCP/Azure), still set MEDIA_ROOT and MEDIA_URL
        # These are needed for our storage handler to work correctly
        MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
        MEDIA_URL = '/media/'
        
        STORAGES = {
            "default": {
                "BACKEND": config['backend'],
                "OPTIONS": config['options'],
            },
            "staticfiles": {
                "BACKEND": config['backend'],
                "OPTIONS": config['options'],
            },
        }
else:
    raise ValueError(
        f"Unsupported STORAGE_CLOUD_PROVIDER: {STORAGE_CLOUD_PROVIDER}. "
        f"Supported values: {', '.join(STORAGE_BACKENDS.keys())}"
    )


# AWS Configurations
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_SERIALIZER': 'chatbot.serializers.ProfileTokenObtainPairSerializer'
}

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = None


sentry_sdk.init(
    dsn=os.getenv('SENTRY_DSN'),
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
)

JAZZMIN_SETTINGS = {
    'site_title': 'Shikshalokam',
    'site_header': 'Shikshalokam',
    'site_brand': ' ',
    'site_logo': 'fe-images/PNG/Shikshalokam/shikshalokam-logo.png',
    'login_logo': 'fe-images/PNG/Shikshalokam/shikshalokam-logo.png',
    'site_logo_classes': 'img-fluid',
    'welcome_sign': '',
    'copyright': 'Shikshalokam',
    'show_ui_builder': False,
    'changeform_format': 'single',

}

JAZZMIN_UI_TWEAKS = {
    'navbar_fixed': True
}

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'debug.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 30,     # Keep 30 backup copies
            'formatter': 'verbose',
            "delay": False,
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'info.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 30,     # Keep 30 backup copies
            'formatter': 'verbose',
            "delay": False,
        },
        'warning_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'error.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 30,     # Keep 30 backup copies
            'formatter': 'verbose',
            "delay": False,
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'error.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 30,     # Keep 30 backup copies
            'formatter': 'verbose',
            "delay": False,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['debug_file', 'info_file', 'warning_file', 'error_file'],
            'level': os.getenv('DEFAULT_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
}

ASGI_APPLICATION_SHUTDOWN_TIMEOUT = 30

CRONJOBS = [
    # ('30 2 * * *', 'chatbot.cron_tasks.chaupal.chaupal_cront_tasks.handle_story_cleanup_cron',
    #  '>> /tmp/handle_story_cleanup_cron.log 2>&1'),
    ('30 3 * * *', 'chatbot.cron_tasks.chaupal.chaupal_cront_tasks.handle_village_ingestion_cron',
     '>> /tmp/handle_village_ingestion_cron.log 2>&1'),
    ('0 22 * * *', 'chatbot.cron_tasks.translation_cron.handle_non_english_fix_cron',
     '>> /tmp/handle_non_english_fix_cron.log 2>&1'),
     ('0 12 * * *', 'chatbot.cron_tasks.delhi_shiksha_samvad.story_creation.create_story',
    '>> /tmp/delhi_shiksha_samvad_story_creation.log 2>&1'),
    ('0 12 * * *', 'chatbot.cron_tasks.shiksha_samvad.story_creation.create_story',
    '>> /tmp/shiksha_samvad_story_creation.log 2>&1'),
    ('0 */2 * * *', 'chatbot.cron_tasks.telangana_ptm_pilot.school_classification.main',
    '>> /tmp/telangana_ptm_pilot_school_classification.log 2>&1'),
    ('15 */2 * * *', 'chatbot.cron_tasks.telangana_ptm_pilot.metrics_extraction.extract_metrics',
    '>> /tmp/telangana_ptm_pilot_metrics_extraction.log 2>&1'),
]